# Generated by Django 5.0.1 on 2024-02-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_application', '0002_rename_student_studentinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='register_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='englishmarks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='mathsmarks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='sciencemarks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='socialmarks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='tamilmarks',
            field=models.IntegerField(default=0),
        ),
    ]
