# Generated by Django 5.0.1 on 2024-02-06 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_application', '0003_login_page_register_page_studentinfo_englishmarks_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentInfo',
            new_name='Student_Info',
        ),
    ]
